### ISSUE TITLE
目前代码还可用吗？

### ISSUE THREAD

**Issue by aanoway** [srx-2000/git_spider#2]
可以应付安居客目前的反爬封ip吗？

**Comment by srx-2000** [comment]
嗯嗯，截止到2021.7.11还是可以使用的（需要自己替换一下cookie），但由于没有接入ip池，可能只能小范围的爬取

**Comment by srx-2000** [comment]
现已在代码中添加了代理池，经测试已经完美封ip的问题了，代理池使用方法详见https://github.com/srx-2000/git_spider/tree/master/proxy_pool

**Comment by aanoway** [comment]
好的好的，谢谢！ 我学习一下




| |
Jianzhang Zhao
***@***.***
|

Signature is customized by Netease Mail Master

在2021年08月11日 17:09，備 写道：

现已在代码中添加了代理池，经测试已经完美封ip的问题了，代理池使用方法详见https://github.com/srx-2000/git_spider/tree/master/proxy_pool

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
