### ISSUE TITLE
小报童API的sign参数应该如何破解？

### ISSUE THREAD

**Issue by eli-yip** [srx-2000/git_spider#44]
`xiaobot.net`的api有一个`sign`参数，翻阅js代码没有找到好的办法，大佬有兴趣尝试破解一下吗，感谢～

**Comment by srx-2000** [comment]
> `xiaobot.net`的api有一个`sign`参数，翻阅js代码没有找到好的办法，大佬有兴趣尝试破解一下吗，感谢～

给一个完整的链接看看？我这边看了你发的xiaobot.net这个，没找到有什么值得爬的数据或者api，还是说这是个app？app我好想也没找到

**Comment by srx-2000** [comment]
> xiaobot.net

em....我这边试了下，可能由于我这边没有付费，我在他的那个订阅号里找不到任何内容，如果你还需要我的帮助，可以加一下我的qq，可能会需要你那边提供一些抓包截图或者账号啥的，1601684622
